language: go

go:
  - 1.4.3
  - release
  - tip


install:
  - go version
  - export GOBIN="$GOPATH/bin"
  - export PATH="$PATH:$GOBIN"
  - go env
  - go get github.com/gorilla/websocket
  - go get github.com/fluffle/goirc/client